version: "3"
networks: 
  vote: 
    driver: bridge

volumes: 
   db-data: 

services: 
    vote: 
      image: ramrajkandasamy/vote:master
      ports: 
        - 5000:80
      networks: 
        - vote
      depends_on: 
        - redis

    redis: 
      image: redis:alpine
      networks: 
        - vote
    
    worker: 
      image: ramrajkandasamy/worker:master
      networks: 
        - vote
      depends_on: 
        - redis
 
    db: 
      image: postgres:9.4
      networks: 
        - vote
      volumes:
        - "db-data:/var/lib/postgresql/data"
   
    results: 
      image: ramrajkandasamy/result:master
      ports:
        - 5001:4000
      networks: 
        - vote
    
